### ISSUE TITLE
Lesson 22: Broken link to starter files

### ISSUE THREAD

**Issue by davidwittenbrink** [Andy-set-studio/learneleventyfromscratch.com#4]
Hi!

I just started with [Lesson 22](https://learneleventyfromscratch.com/lesson/22.html#starter-files) (Global CSS and design tokens) and found a small issue: The links to the starter files seem to be broken. The code references `{{starterFiles }}` but I didn't find the variable in the project.
https://github.com/andy-piccalilli/learneleventyfromscratch.com/blob/df1e3908f0797fdfa0b97707cb000d89bc1a1a42/docs/lesson/22.md#L17-L19

I have the zip file on my disk and also found the old download link from https://piccalil.li which is still working.
If you want I can send a PR to fix this by either using the old Piccalilli link or adding the zip file to a `./public/files` directory. Do you have a preference?

**Comment by andy-piccalilli** [comment]
Good catch. Just switched that out. Thank you!
